version: '3.4'

services:
  catalog.api:
    image: checkout/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: checkout/basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  desktop.api:
    image: checkout/desktop.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Gateways/Desktop/Desktop.Api/Dockerfile
    depends_on:
      - catalog.api
      - basket.api

